title: "Navdeep kaur"
description: "Currently I am a student and pursuing bachelors in Applied Data Science."
theme: jekyll-theme-cayman

author:
  name: "Navdeep kaur"
  email: "navdeepkxur@gmail.com"

header_pages:
  - index.md
  - hobbies.md

github_username: Navdeepkaur36
linkedin_username: No linkedin username
