title: "Navdeep kaur"
description: "Currently I am a student and pursuing bachelors in Applied Data Science."
theme: minima

author:
  name: "Navdeep kaur"
  email: "navdeepkxur@gmail.com"

header_pages:
  - index.md

github_username: Navdeepkaur36
linkedin_username: No linkedin username
